# -*- coding: utf-8 -*-
"""best.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DVPwtlcwFTj5DFE2qlCXw1y0yEYX6Sql
"""

import sys
import os
import pandas as pd

blastn_file = sys.argv[1]
output_directory = sys.argv[2]
base_name = sys.argv[3]

# Read the BLASTN output file as a DataFrame
blastn_data = pd.read_csv(blastn_file, sep='\t', header=None)

# Convert the last column to numeric (Bitscore)
blastn_data[11] = pd.to_numeric(blastn_data[11], errors='coerce')

# Sort the DataFrame by the Bitscore column in descending order
sorted_data = blastn_data.sort_values(by=11, ascending=False)

# Drop duplicates based on the unique Node (column 0) while keeping only the first occurrence
selected_reads = sorted_data.drop_duplicates(subset=0, keep='first')

# Save the selected hits to a file
output_file = os.path.join(output_directory, f"{base_name}_best_hits.blastn")
selected_reads.to_csv(output_file, sep='\t', index=False, header=False)

print("Saved best hits to:", output_file)