# -*- coding: utf-8 -*-
"""QC_select.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x6xmO0Q8jy_lcnPnEGQ4hEGl-aqYGFh2
"""

import sys
import os
import pandas as pd
import csv

blastn_file = sys.argv[1]
output_directory = sys.argv[2]
min_identity = float(sys.argv[3])
min_alignment_length = float(sys.argv[4])
max_evalue = float(sys.argv[5])
min_coverage = float(sys.argv[6])
base_name = sys.argv[7]

# Read the BLASTN output file as a DataFrame
blastn_data = pd.read_csv(blastn_file, sep='\t', header=None)

# Extract the coverage value from the first column
blastn_data['Coverage'] = blastn_data[0].str.extract(r'cov_([\d.]+)').astype(float)

# Apply the QC criteria to select the good quality reads
selected_reads = blastn_data[(blastn_data[2] > min_identity) &
                             (blastn_data[3] > min_alignment_length) &
                             (blastn_data[10] < max_evalue) &
                             (blastn_data['Coverage'] > min_coverage)]

# Save the selected Query ID and Subject ID to a file
output_file = os.path.join(output_directory, f"{base_name}_selected_reads.blastn")
selected_reads.to_csv(output_file, sep='\t', index=False, header=False, quoting=csv.QUOTE_NONE, escapechar='\\')
